twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservice
    - Kafka
    - ElasticSearch
  welcome-message: Hello Micros!!
  enable-v2-tweets: true
  twitter-v2-base-url: https://api.twitter.com/2/tweets/search/stream?tweet.fields=created_at&expansions=author_id
  twitter-v2-rules-based-url: https://api.twitter.com/2/tweets/search/stream/rules
  twitter-v2-bearer-token: AAAAAAAAAAAAAAAAAAAAALL5iwEAAAAAgTuLAzrtYKqd%2BF%2FeP5ChEv8Xg8o%3DR7HYZS35pd8Iiedx3yuFByFjMUjPOpwYVKtuKjj7Ts7Zybk5Nu

retry-config:
  initial-interval: 1000
  max-interval: 50000
  multiplier: 2.0
  max-attempts: 10
  sleep-time: 2000

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key:  schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-topic
  num-of-partitions: 3
  replication-factor: 3
kafka-producer-config:
  key-serialization-class: org.apache.kafka.common.serialization.LongSerializer
  value-serialization-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 10
